using Pathfinding;
using System.Collections;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;
using UnityEngine;

public class EnemyAISecindLVL : MonoBehaviour
{
    public Transform target;

    public float speed = 200f;
    public float NextWaypointDistance = 3f;
    public float borderAttakX;
    public float borderAttakY;

    public Transform enemyGFX;

    Path path;
    int currentWaypoint = 0;
    bool reacheadEndOfPath = false;

    Seeker seeker;
    Rigidbody2D rb;

    // Start is called before the first frame update
    void Start()
    {
        seeker = GetComponent<Seeker>();
        rb = GetComponent<Rigidbody2D>();
        InvokeRepeating("UpdatePath", 0f, .5f);
        seeker.StartPath(rb.position, target.position, OnPathComplete);
    }

    void UpdatePath()
    {
        if (seeker.IsDone())
        {
            seeker.StartPath(rb.position, target.position, OnPathComplete);
        }
    }

    void OnPathComplete(Path p)
    {
        if (!p.error)
        {
            path = p;
            currentWaypoint = 0;
        }
    }

    // Update is called once per frame
    void Update()
    {
        if (path == null)
            return;
        if (currentWaypoint >= path.vectorPath.Count)
        {
            reacheadEndOfPath = true;
            return;

        }
        else
        {
            reacheadEndOfPath = false;
        }
        if (target.position.x > borderAttakX && target.position.y >borderAttakY)
        {

            Vector2 direction = ((Vector2)path.vectorPath[currentWaypoint] - rb.position).normalized;
            Vector2 force = direction * speed * Time.deltaTime;

            rb.AddForce(force);

            float distance = Vector2.Distance(rb.position, path.vectorPath[currentWaypoint]);

            if (distance < NextWaypointDistance)
            {
                currentWaypoint++;
            }

            if (force.x >= 0.01f)  //Поворот изображения
            {
                enemyGFX.localScale = new Vector3(-1f, 1f, 1f) * 4; //применяется к оригинальному размеру, поэтому домнажаем для увеличения
            }
            else if (force.x <= -0.01f)
            {
                enemyGFX.localScale = new Vector3(1f, 1f, 1f) * 4;
            }
        }
    }
}
